denodrivers/postgres

- .travis.yml
- README.md
- client.ts
- connection.ts
- connection_params.ts
- test.ts
- tests/client.ts
- tests/connection_params.ts
- tests/queries.ts
- tests/utils.ts
- utils.ts
> Support DSN-style and env variables connection param

- .travis.yml
- deps.ts
- packet_writer.ts
- test.ts
- tests/client.ts
- tests/connection_params.ts
- tests/encode.ts
- tests/queries.ts
- tests/utils.ts
> Update deno_std to v0.2.8

- encode.ts
- query.ts
> Change type of query args

- README.md
- docs/README.md
- docs/index.html
Basic setup with [docsify](https://docsify.js.org)
> Documentation

- client.ts
- mod.ts
- pool.ts
- tests/client.ts
- tests/pool.ts
> Fix makeshift pool

- deferred.ts
- pool.ts
- tests/pool.ts
part of https://github.com/bartlomieju/deno-postgres/issues/49
lazy to create connections from 1 to max pool size
> lazy create connection

- deps.ts
- pool.ts
- tests/pool.ts
> Repair the potential danger of depleting connection pools

- decode.ts
- encode.ts
- tests/constants.ts
- tests/queries.ts
based on node implementation of postgres-bytea: 
https://github.com/bendrucker/postgres-bytea/blob/master/index.js
> bytea type implemented

- README.md
> chore: add contributing guidelines

- .travis.yml
- connection_params.ts
- deferred.ts
- deps.ts
and bump deno to v0.22.0.
cc @bartlomieju
> Use deferred from std@v0.22.0

- decode.ts
- tests/data_types.ts
> fix: treat PostgreSQL's bigint type as String instead of Number

- decode.ts
- tests/data_types.ts
> fix: add support for numeric type

- decode.ts
- tests/data_types.ts
> fix: add support for void type

- pool.ts
I'm trying to port https://github.com/joeandaverde/tinypg to Deno using this driver. 
Running into a few issues and fixing along the way.
> prevent undefined error when using accessors prior to pool connecting.

- decode.ts
- tests/data_types.ts
Resolves: error: Uncaught Error: Don't know how to parse column type: 1042
> resloves #99

- .github/workflows/ci.yml
- client.ts
- connection.ts
- decode.ts
- encode.ts
- error.ts
- pool.ts
- query.ts
Closes https://github.com/deno-postgres/deno-postgres/issues/138
> chore: add deno lint to ci

- .github/workflows/ci.yml
- array_parser.ts
- connection.ts
- decode.ts
- deps.ts
- error.ts
- query.ts
- tests/constants.ts
- tests/helpers.ts
- tests/queries.ts
> Update to 1.4.0 and workaround TS1371

- decode.ts
- oid.ts
- tests/data_types.ts
> Add bigint support

- decode.ts
- oid.ts
- tests/data_types.ts
> Add xid support

- client.ts
- connection.ts
- pool.ts
- query.ts
- tests/data_types.ts
- tests/pool.ts
- tests/queries.ts
> Add generic return types

- connection.ts
- tests/queries.ts
> fix: Don't panic on `name_too_long` error

- client.ts
- connection.ts
- pool.ts
This should make it easier to implement new features by simplyfing the message send/recieve workflow implemented, good exercise to understand how postgres connections actually work!
> Refactor connections

- .github/workflows/ci.yml
- README.md
- connection.ts
- connection_params.ts
- docs/README.md
- docs/index.html
- test.ts
- tests/data_types.ts
> SSL support

- client.ts
- connection/connection.ts
- pool.ts
- query/query.ts
This refactor will make it easy to create the transaction abstractions
> refactor: Move result type to Query constructor

- Dockerfile
- connection/connection.ts
- deps.ts
- query/query.ts
- tests/data_types_test.ts
- tests/test_deps.ts
> chore: Bump to Deno 1.9 and std 0.93.0

- connection/connection.ts
- docker-compose.yml
- docker/postgres/data/pg_hba.conf
- docker/postgres/data/postgresql.conf
- docker/postgres/init/initialize_test_server.sh
- docker/postgres_invalid_tls/data/pg_hba.conf
- docker/postgres_invalid_tls/data/postgresql.conf
- docker/postgres_invalid_tls/init/initialize_test_server.sh
- docs/README.md
- tests/config.json
- tests/config.ts
- tests/connection_test.ts
> fix: Throw error on invalid TLS connection

- README.md
Just noticed a few typos so I ran the `README.md` through a spell check. Looks like a great project! :)
> Spellling and grammar

- client.ts
- connection/connection.ts
- connection/connection_params.ts
- connection/warning.ts
- docker-compose.yml
- docs/README.md
- mod.ts
- pool.ts
- query/query.ts
- tests/config.ts
- tests/connection_params_test.ts
- tests/connection_test.ts
- tests/query_client_test.ts
- tests/workers/postgres_server.ts
> feat: Add reconnection configuration on Client

- docs/README.md
> docs: Fix pool abstraction example error handling

- connection/connection.ts
- connection/connection_params.ts
- tests/config.ts
- tests/connection_params_test.ts
Adds support for sslmode "disable".
> feat: add support for sslmode=disable

- connection/connection.ts
- connection/connection_params.ts
- docker/postgres_invalid_tls/data/pg_hba.conf
- tests/connection_params_test.ts
- tests/connection_test.ts
> fix: Skip TLS encryption correctly and add regression test

- connection/connection.ts
- tests/query_client_test.ts
> fix: Handle ready message on query preparation

- connection/connection.ts
- tests/query_client_test.ts
> fix: Handle ready message on prepared statements

- query/array_parser.ts
- query/decoders.ts
- tests/data_types_test.ts
> fix: Detect array delimiter based on column type

- docs/README.md
- pool.ts
- tests/pool_test.ts
- tests/query_client_test.ts
> docs: Fix pool examples

- connection/connection.ts
- tests/query_client_test.ts
> fix: Handle parameter status messages

- query/decode.ts
- query/oid.ts
> fix: Typo on oid for uuid array

- connection/connection.ts
- tests/config.ts
- tests/connection_test.ts
- tests/test_deps.ts
> fix: Handle unexpected database disconnection

- .github/workflows/ci.yml
- Dockerfile
- docker-compose.yml
- tests/auth_test.ts
> chore: Add no-check testing step

- client.ts
- docs/README.md
- mod.ts
- query/encode.ts
- query/query.ts
- query/transaction.ts
- tests/data_types_test.ts
- tests/encode_test.ts
- tests/pool_test.ts
- tests/query_client_test.ts
> Named parameters

- query/transaction.ts
- tests/query_client_test.ts
> fix: Fix transaction behavior for clientArray

- docs/README.md
> docs: Remove references to transaction.end

- query/transaction.ts
This PR attempts to remove unnecessary “there is no transaction in progress” warning. See [the discussion](https://github.com/denodrivers/postgres/issues/392) for details.
> fix: remove “there is no transaction in progress” warning (#392)

- docs/README.md
> Minor README.md update

- connection/connection.ts
- connection/connection_params.ts
- docs/README.md
> feat: Add interval option for connections

- connection/connection.ts
> fix: Don't send options connection parameter unless supplied

- .github/workflows/ci.yml
- Dockerfile
- README.md
- connection/connection_params.ts
- connection/scram.ts
- deps.ts
- docker-compose.yml
- docs/README.md
- query/query.ts
- query/transaction.ts
- tests/connection_params_test.ts
- tests/connection_test.ts
- tests/data_types_test.ts
- tests/query_client_test.ts
- tests/test_deps.ts
> Bump to Deno 1.26.2

- README.md
- docs/README.md
This will make upcoming JSR support a little cleaner.
> docs: remove pinned version imports

- query/query.ts
> fix: add CREATE to CommandType

- connection/connection.ts
- connection/message_code.ts
This is a fix for this error: https://github.com/denodrivers/postgres/issues/495
> Update to allow NOTICEs on connect.
