denodrivers/postgres

- encode.ts
- query.ts
- tests/encode.ts
- utils.ts
Closes #13 
Moved logic of encoding JS types to `encode.ts`.
Also added `encoder` argument to `QueryConfig` - this will allow users to extend this lib capabilities for custom types.
> Refactor encoding query args

- client.ts
- connection.ts
- deps.ts
- pool.ts
- query.ts
- tests/pool.ts
- tests/queries.ts
This means they can each be run independently.
fixes #10
> Refactor query and pool tests to use a shared setup

- query.ts
Hello! Thanks for the lib 🙏 
Wondering if there was a reason QueryResult.rowDescription was private? Since the result rows come back to the caller in the form of an array, this info is particularly useful for mapping a single row result back into an object with column names for keys, a la:
```
export const mapResult = (result: QueryResult) =>
result.rows.map(row =>
row.reduce((record, column, index) => {
const columnName = result.rowDescription.columns[index].name;
return {
...record,
[columnName]: column
};
})
);
```
> Make QueryResult.rowDescription public

- decode.ts
Resolves #76 
This PR fixes 'name' column type parsing method is not implemented.
This change ensures that the 'name' type is handled properly and the following query can be executed without error.
SELECT * FROM information_schema.tables
> fix: Add 'name' column type to decodeText (#76)

- utils.ts
This PR fixes hashMd5Password function. 
This function is used like the below in `connection.ts`:
```ts
const password = hashMd5Password(
this.connParams.password,
this.connParams.user,
salt
);
```
However the paramter order of user and password is reversed in the function definition, and therefore this produces wrong md5 hash for authentication.
I checked I can connect to my postgres instance on AWS RDS with this patch applied.
> Fix hash md5 password

- deps.ts
- test.ts
- test_deps.ts
- tests/client.ts
- tests/connection_params.ts
- tests/data_types.ts
- tests/encode.ts
- tests/helpers.ts
- tests/pool.ts
- tests/queries.ts
- tests/utils.ts
This PR separates `test_deps.ts` from `deps.ts` and reduces the download size of the library.
closes #84
> refactor: separate test_deps.ts from deps.ts

- decode.ts
- tests/data_types.ts
- This PR closes #88.
- Added support for oid types.
- https://www.postgresql.org/docs/11/datatype-oid.html
- Ran `deno fmt` against `decode.ts` and `tests/data_types.ts`.
> Add support for oid types

- error.ts
Fixes #103 
Fixed some typos on PostgresError field interface.
I think the parameter assignation should be handled differently, cause currently it is overlooking the interface and making it hard to spot errors like this
> Fix typos on PostgresError Interface

- .travis.yml
- connection.ts
- connection_params.ts
- deferred.ts
- deps.ts
- encode.ts
- oid.ts
- pool.ts
- query.ts
- test_deps.ts
- tests/connection_params.ts
- tests/constants.ts
- tests/data_types.ts
- tests/encode.ts
- tests/helpers.ts
- tests/pool.ts
- tests/utils.ts
- utils.ts
This PR closes #105.
- Run `deno fmt` for all TypeScript files (69e93cb)
- Bumped Deno to v0.39.0 in CI
- Bumped deno_std to v0.39.0
- Bumped checksum to v1.2.0
- compilation of checksum@v1.0.1 fails on Deno@v0.39.0
- Fixed the `Pool.end` because it leaks resources ([8b73869](https://github.com/buildondata/deno-postgres/pull/106/commits/8b73869c72063dd33e6350936ad45473f1ca87b2#diff-abbe517e83766bfd209816919082cb37))
> chore: bump Deno to v0.39.0

- README.md
@bartlomieju I realized that we forgot to update the CI badge in the readme.
This pr closes #67
> Replace CI badge from Travis to Github

- .github/workflows/ci.yml
- README.md
- connection_params.ts
- deps.ts
- test.ts
- test_deps.ts
- tests/client.ts
- tests/connection_params.ts
- tests/encode.ts
- tests/utils.ts
- utils.ts
This PR updates Deno-Postgres to work under Deno v0.42
> Update to Deno v0.42

- client.ts
- connection.ts
- connection_params.ts
- docs/README.md
- pool.ts
- test_deps.ts
- tests/connection_params.ts
- tests/constants.ts
- tests/utils.ts
- utils.ts
Closes #113 
I took the liberty to also refactor the creation of the connection_params.ts params because I found the code a bit hard to follow and modify. Let me know what you think.
I also think `parseDsn` should be moved into `connection_params.ts` and tested through createParams instead. If you agree, I'll do that as well.
> rename connection params host->hostname and change port type

- utils.ts
The URL api is aligned to match the one in the browser, which mean that in both cases passing a connection string with the following format:
```log
postgres://fizz:buzz@deno.land:8000/test_database?application_name=myapp
```
The URL api won't parse the url correctly due to the API not recognizing the protocol/driver in the url, that is why this PR replaces the protocol with `http` in order to parse the url correctly through the URL api.
> [Fix] Connection string parsing

- connection.ts
- tests/queries.ts
This ensures a Client can not do concurrent queries over the same connection
Fixes #123 
Note: This may also need to be done on connect/_startup, as if you call that twice/concurrently there could be an issue 🤷 , I haven't tested that.
> Use a per Connection query lock

- docs/README.md
Currently the website: https://deno-postgres.com/#/?id=queries
Has the following example:
```ts
import { Client } from "https://deno.land/x/postgres/mod.ts";
async function main() {
const client = new Client({
user: "user",
database: "test",
host: "localhost",
port: "5432"
});
await client.connect();
const result = await client.query("SELECT * FROM people;");
console.log(result.rows);
await client.end();
}
main();
```
But when running the example locally it fails with the following error:
```
error: TS2345 [ERROR]: Argument of type '{ user: string; database: string; host: string; port: number; }' is not assignable to parameter of type 'string | ConnectionOptions | undefined'.
Object literal may only specify known properties, and 'host' does not exist in type 'ConnectionOptions'.
host: …
```
> Fix docs to match API

- array_parser.ts
- decode.ts
- tests/data_types.ts
Fixes #136 #137 
Copied/Ported postgres-array
Added oid handling in decode
Fixed int2 and int4 handling for array like fields
Added bunch of tests for array and nested array types
> Add functionality for array like types

- .github/workflows/ci.yml
- array_parser.ts
- deps.ts
- packet_reader.ts
- test_deps.ts
- tests/client.ts
- Bumped Deno to v1.2.0 in CI.
- Bumped std to v0.61.0.
- `copyBytes` has been moved from `std/io/util.ts` to `std/bytes/mod.ts`.
- `assertStrContains` has been renamed to `assertStringContains`.
- Fixed `array_parser.ts` and `packet_reader.ts` to pass "deno lint".
> chore: bump Deno to v1.2.0

- pool.ts
Fixes #127 
Renames `Pool#_ready` to `Pool#ready`, and exposes it
> [#127] Expose and rename _ready prop on Pool class

- docs/README.md
Fixes #145 
Fixes #147 
Adds documentation on the returned type for a query. This fixes issues for people who use `deno lint` (it throws a lot of errors when executing on `result` or `client`)
> [update-docs] Add further documentation

- .github/workflows/ci.yml
- connection.ts
- deps.ts
- test_deps.ts
- utils.ts
- Replaced x/checksum library for std/hash implementation
- Upgraded Deno to v1.2.2 and std to v0.63.0
Please add a release tag to this so people don't have to pull from master or commit hash
(_Real shocking images_)
> Bump Deno to v1.2.2, replace checksum lib for std/hash

- docs/README.md
The port field in the client object is of type `number` but in the examples it is showcased as a string
```javascript
const client = new Client({
user: "user",
database: "test",
hostname: "localhost",
port: "5432"
});
```
Which raised the following error on build: 
`error: Uncaught InvalidData: data did not match any variant of untagged enum ArgsEnum`
> Documentation: Port is of type number but examples uses string

- connection.ts
- deps.ts
- test_deps.ts
This updates the std dependencies to 0.67.0, to work with Deno 1.3.0.
The only notable change required for this is the removal of the `delete` statements for various non-null asserted members of the `Connection` class. TS4.0 made deleting non-optional members a compile-time error.
Resolves #165
> chore: update for deno 1.3.0 & std 0.67.0 (resolves #165)

- docs/README.md
Ther error in documentation explicitly used `await` in a non async function. This means that the examples are incorrect and should be fixed.
BEFORE:
```typescript
import { Pool } from "https://deno.land/x/postgres@v0.4.0/mod.ts";
import { PoolClient } from "https://deno.land/x/postgres@v0.4.0/client.ts";
const POOL_CONNECTIONS = 20;
const dbPool = new Pool({
user: "user",
password: "password",
database: "database",
hostname: "hostname",
port: 5432,
}, POOL_CONNECTIONS);
function runQuery (query: string) {
const client: PoolClient = await dbPool.connect();
const dbResult = await client.query(query);
client.release();
return dbResult
}
runQuery("SELECT * FROM users;");
runQuery("SELECT * FROM users WHERE id = '1';");
```
AFTER:
```typescript
import { Pool } from …
```
> Fixed Bug in README.md

- array_parser.ts
This PR follows up to #166.
- Bump deno to v1.3.2 in CI
- Fix lint errors
> chore(lint): don't ignore ban-types

- connection.ts
- decode.ts
- deps.ts
- oid.ts
- tests/data_types.ts
- tests/pool.ts
- tests/utils.ts
If you could add the "hacktoberfest-accepted" label to this PR it would be great!
> Add json array and jsonb array type

- decode.ts
- tests/data_types.ts
> Add bool and bytea array types

- client.ts
- connection.ts
- pool.ts
- query.ts
- tests/client.ts
- tests/data_types.ts
- tests/helpers.ts
- tests/pool.ts
- tests/queries.ts
Towards #134
Also this improves performance greatly for object based queries, since you don't have to recast as object with `rowsOfObjects`
> Decouple query as array and as object

- .github/workflows/ci.yml
- deps.ts
- test_deps.ts
We are using std 0.85.0, and hope to upgrade the deno version to reduce unnecessary dependencies.
> feat: Update to Deno 1.7.1 and std 0.85.0

- connection/connection_params.ts
- tests/connection_params_test.ts
Adds postgresql:// driver name support to the dsn format for compatibility with other postgresql clients. This can be really handy in situations where DATABASE_URL environment variables are being used and set automatically by the hosting platform.
> feat: Allow postgresql:// dsn.driver for compatibility

- connection/connection_params.ts
- tests/connection_params_test.ts
libpq dsn support includes an `sslmode` flag to specify various levels of TLS requirement. This PR updates the DSN handling to allow `sslmode=prefer` (which seems to be the library's default) and `sslmode=require` to set `tls.enforce` on the connection.
@Soremwar I'm hoping in a near future PR to also get specifying a root cert set up as well and getting cert verification going as well, if you're cool with that.
> feat: sslmode dsn support

- connection/deferred.ts
- docs/README.md
- pool.ts
- tests/pool_test.ts
- This allows users to reinitialize a pool connection after it as been closed
- This changes pool behavior by not initiating any connection before a client is requested, previous behavior opened one connection in advance
> refactor: Cleanup pool connection and add pool docs

- README.md
- connection/connection.ts
This PR should close #281 as it removes the generic from Deno.Conn. I am not sure which implications it has by changing this, but from the tests, it seems like everything still works as intended.
> fixed Deno.conn

- README.md
- docker-compose.yml
- tests/config.json
- tests/config.ts
This PR adds an option to run the tests on the developer machine, allowing the possibility of using the inspector while testing the application
> chore: Setup testing on host machine

- query/encode.ts
- tests/encode_test.ts
```diff
-val < 10 ? `0${val.toString(16)}` : val.toString(16))
+val < 0x10 ? `0${val.toString(16)}` : val.toString(16))
```
E.g. when `val` is 11 it should encode as `"0b"` but 11 is not less than 10 so it doesn't get padded.
This surfaces from postgres as
`PostgresError: invalid hexadecimal data: odd number of digits`
when trying to use `bytea`.
> Fix threshold for applying 0 padding when encoding hex

- docs/README.md
only fixed typo required -> require  
> Only 'disable', 'require', and 'prefer' are supported
https://github.com/denodrivers/postgres/blob/160608b0617e6dc3dae156a90f099f4022a1a081/connection/connection_params.ts#L145
> chore: fixed typo required -> require

- deps.ts
- query/decoders.ts
- tests/data_types_test.ts
- tests/test_deps.ts
The previous implementation had some important flaws that went unnoticed until now, this simply replaces it with std/date parsing
> fix: Parse date string correctly

- connection/connection.ts
- connection/connection_params.ts
- docs/README.md
- tests/config.ts
In Deno 1.15 CA files can be specified as PEM encoded cert
strings, rather than as file paths to the PEM encoded certs.
See https://github.com/denoland/deno/commit/0d7a417f332a57fb3e89250a1ce250b929d0b2f7
Dependant on #345.
> feat: use caCertificates instead of caFile

- query/decode.ts
- query/query.ts
- tests/query_client_test.ts
This fixes an incorrect transformation of camelcase names such as `variableX_y` -> `variablexY` instead of `variableXY` while also validating that the implicit fields returned by the database aren't duplicated
> fix: Camelcase implementation and duplicated field name handling

- connection/auth.ts
- connection/connection.ts
- deps.ts
- tests/auth_test.ts
- tests/connection_test.ts
- tests/query_client_test.ts
- tests/test_deps.ts
This increases library size by a good chunk, still negligible though considering std/hash would have been removed eventually
Before: `dependencies: 52 unique (total 315.58KB)`
After: `dependencies: 55 unique (total 521.96KB)`
> chore: Fix deprecated dependencies

- tests/pool_test.ts
- utils/deferred.ts
This PR fixes #378 (concurrent connect-then-release cycles may throw) by modifying `DeferredAccessStack` (`push` and `pop` to be specific). `deferred.resolve` and `await d` is executed asynchronously (other statements may be executed in between); access to `#elements` is not performed as expected (racing happens).
I see some overlapping logic between `DeferredStack` and `DeferredAccessStack`. To keep consistency, `push` and `pop` of `DeferredStack` are also modified using the same pattern. `#array` is also renamed to `#elements`. I am not sure if the modification to `DeferredStack` solves real-world problems but I think there’re chances these two classes will be consolidated/combined/refactored I do not want such discrepancy confuses somebody then.
A test case is included. Please let me …
> fix: concurrent connect-then-release cycles do not throw (#378)

- pool.ts
'await' has no effect for `.release()`.
https://github.com/denodrivers/postgres/issues/332
> chore: update comments

- connection/auth.ts
- connection/scram.ts
- deps.ts
- query/decoders.ts
- tests/connection_test.ts
- tests/data_types_test.ts
- tests/test_deps.ts
- utils/deferred.ts
This PR bumps the `std` dependencies from `0.160.0` to the latest `0.180.0` (as of writing). Breaking changes upstream (i.e., renamed exports, moved files, etc.) have been addressed accordingly.
While I was bumping the versions, I also refactored some exports such that we now prefer importing submodules instead of the more general `mod.ts` files (which downloads a bunch of unneeded files).
> deps(std): bump dependencies and prefer their lighter submodules

- client.ts
- connection/connection.ts
- query/query.ts
- query/transaction.ts
> chore: add missing return types

- README.md
- client.ts
- client/error.ts
- connection/connection.ts
- connection/connection_params.ts
- connection/message.ts
- connection/message_code.ts
- connection/scram.ts
- docker-compose.yml
- pool.ts
- query/array_parser.ts
- query/decode.ts
- query/decoders.ts
- query/query.ts
- query/transaction.ts
- tests/README.md
- tests/data_types_test.ts
- tests/decode_test.ts
- utils/deferred.ts
- utils/utils.ts
Fixes #432
- On value decode error, log error and return `null` (previously bubbled the error up)
- Parse `Float4` to number (previously returned as string)
- Format all project files using `deno fmt`
- Update PG geometric type decoders with improved parse checks and error messaging
> Update decoders to parse float and return null on error

- client.ts
- client/error.ts
- connection/connection_params.ts
- connection/message.ts
- mod.ts
- pool.ts
- query/encode.ts
- query/query.ts
- query/transaction.ts
Fixes #448
- Add JSDocs
- Export more types and classes
> Add JSDocs

- .github/workflows/publish_jsr.yml
- README.md
Couple bits to add to recent JSR support.
> chore: cleanups and documentation relating to JSR

- connection/connection.ts
- connection/connection_params.ts
- query/decode.ts
- query/query.ts
- tests/config.ts
- tests/decode_test.ts
- tests/query_client_test.ts
FIxes #450
It gives developers control over the decoding strategy employed by the driver when returning row data.
The default is `auto` (the current behavior) while adding `string` mode so all data is returned as a string and the user can take care of parsing the data in their application.
> Add decode strategy control

- README.md
"User experience" typically implies end-users as opposed to the software developers. "Developer experience" a better choice IMO since it is a [popular phrase](https://github.blog/2023-06-08-developer-experience-what-is-it-and-why-should-you-care/) and because it is less ambiguous.
> "user experience" -> "developer experience"

- docs/README.md
- query/query.ts
- tests/query_client_test.ts
> Refactor camelCase

- client/error.ts
- connection/connection.ts
- debug.ts
- docs/README.md
- tests/query_client_test.ts
- tests/test_deps.ts
> Add query to error option

- connection/connection_params.ts
- deno.json
- docs/README.md
- query/array_parser.ts
- query/decode.ts
- tests/README.md
- tests/query_client_test.ts
- **feat: add logic to handle array types for custom decoders**
- **chore: update docs**
> Handle array type custom decoders

- client.ts
- query/array_parser.ts
- tests/pool_test.ts
> Allow `using` keyword with pool clients

- .github/workflows/publish_jsr.yml
Currently, the workflow to publish on jsr first modifies the imports, then checks if the formatting is correct.
Since the new imports are shorter, it can happen that an import statements spanning multiple lines, becomes short enough to fit in a single line (which `deno fmt` mandates).
A solution, as proposed in this PR, is to check the formatting before converting the code, and then reformat again after the code is converted.
> chore: correct formatting strategy for publishing on JSR

- connection/connection.ts
Currently, this error gets lost when TLS enforcement is true.
> Log errors when TLS fails

- .github/workflows/publish_jsr.yml
Current JSR package is lagging behind because this job has been failing due to the uncommitted change check, which clashes with formatting & converting steps.
> fix(cd): allow publish of formatted/converted code

- connection/connection_params.ts
- tests/config.ts
Updates usages of of `Deno.errors.PermissionDenied` to also support Deno v2's new `Deno.errors.NotCapable`.
Fixes #491
> fix: Deno 2 permissions system update for ENV

- .github/workflows/publish_jsr.yml
it seems in my efforts to fix the docs tests, I forgot to update the JSR publish workflow. this pr fixes that workflow and it should pass just fine, assuming someone creates the `@db/postgres` package under the JSR scope and links this Github repo
> fix JSR publish workflow
